---
name: Lint Code Base
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Code Base(Expect Lua)
        uses: github/super-linter/slim@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          VALIDATE_LUA: false

      - uses: taiki-e/install-action@v2
        with:
          tool: selene

      - name: Lint Code Base(Lua)
        run: |
          selene . -q

